
drafted_teams = [ "Duke",
        "Kentucky",
        "Southern California",
        "TCU",
        "Saint Mary's (CA)",
        "St. John's (NY)",
        "Indiana",
        "Texas Tech",
        "Missouri",
        "Georgetown",
        "VCU",
        "Michigan", "Purdue",
        "Marquette",
        "Houston",
        "Texas A&M",
        "North Carolina",
        "Maryland",
        "Auburn",
        "Mississippi St.",
        "Oregon",
        "Clemson",
        "Rutgers",
        "Duquesne", "Michigan St.",
        "Arizona",
        "Texas",
        "UConn",
        "San Diego St.",
        "Wisconsin",
        "Virginia",
        "Kansas St.",
        "Dayton",
        "Providence",
        "Oklahoma",
        "Tulane", "Kansas",
        "Fla. Atlantic",
        "Gonzaga",
        "Miami (FL)",
        "Alabama",
        "Villanova",
        "Ohio St.",
        "UCLA",
        "Florida",
        "Iowa St.",
        "Boise St.",
        "Oklahoma St.", "Tennessee",
        "Baylor",
        "Creighton",
        "Arkansas",
        "Illinois",
        "Colorado",
        "Memphis",
        "Xavier",
        "New Mexico",
        "Northwestern",
        "St. Bonaventure",
        "Ole Miss"]

team_mappings = {
    "Michigan State" : "Michigan St.",
    "Florida Atlantic": "Fla. Atlantic",
    "Miami" : "Miami (FL)",
    "San Diego State" : "San Diego St",
    "USC" : "Southern California",
    "Saint Mary's" : "Saint Mary's (CA)",
    "Connecticut" : "UConn", 
    "James Madison" : "James Madison",
    "Mississippi State" : "Mississippi St."
} 
